const foods = [
  {
    name: 'Chicken Breast',
    category: 'Poultry',
    serving: '100g cooked',
    calories: 165,
    fat: 3.6,
    carbs: 0,
    protein: 31,
    fiber: 0,
    sugar: 0,
    sodium: 74,
    ingredients: 'Boneless skinless chicken breast',
    description: 'Lean protein source popular for healthy meal plans.'
  },
  {
    name: 'Salmon Fillet',
    category: 'Seafood',
    serving: '100g cooked',
    calories: 208,
    fat: 13,
    carbs: 0,
    protein: 20,
    fiber: 0,
    sugar: 0,
    sodium: 59,
    ingredients: 'Atlantic salmon',
    description: 'Rich in omega-3 fatty acids with savory taste.'
  },
  {
    name: 'Sweet Potato',
    category: 'Vegetables',
    serving: '1 medium (130g)',
    calories: 112,
    fat: 0.1,
    carbs: 26,
    protein: 2,
    fiber: 4.1,
    sugar: 5.4,
    sodium: 55,
    ingredients: 'Sweet potato',
    description: 'Naturally sweet root vegetable high in fiber and vitamin A.'
  },
  {
    name: 'Banana',
    category: 'Fruits',
    serving: '1 medium (118g)',
    calories: 105,
    fat: 0.4,
    carbs: 27,
    protein: 1.3,
    fiber: 3.1,
    sugar: 14,
    sodium: 1,
    ingredients: 'Banana',
    description: 'Classic fruit with quick energy and potassium.'
  },
  {
    name: 'Greek Yogurt',
    category: 'Dairy',
    serving: '170g',
    calories: 100,
    fat: 0,
    carbs: 6,
    protein: 17,
    fiber: 0,
    sugar: 4,
    sodium: 65,
    ingredients: 'Nonfat plain Greek yogurt',
    description: 'Thick yogurt packed with protein and probiotics.'
  },
  {
    name: 'Quinoa',
    category: 'Grains',
    serving: '185g cooked',
    calories: 222,
    fat: 3.6,
    carbs: 39,
    protein: 8,
    fiber: 5,
    sugar: 1.6,
    sodium: 13,
    ingredients: 'Cooked quinoa',
    description: 'Gluten-free ancient grain with balanced plant protein.'
  },
  {
    name: 'Almonds',
    category: 'Snacks',
    serving: '28g (1 oz)',
    calories: 164,
    fat: 14,
    carbs: 6,
    protein: 6,
    fiber: 3.5,
    sugar: 1.2,
    sodium: 0,
    ingredients: 'Raw almonds',
    description: 'Crunchy nut rich in healthy fats, fiber and micronutrients.'
  },
  {
    name: 'Brown Rice',
    category: 'Grains',
    serving: '195g cooked',
    calories: 216,
    fat: 1.8,
    carbs: 44,
    protein: 5,
    fiber: 3.5,
    sugar: 0.7,
    sodium: 10,
    ingredients: 'Cooked brown rice',
    description: 'Whole grain staple with lasting energy and fiber.'
  },
  {
    name: 'Avocado',
    category: 'Fruits',
    serving: '100g',
    calories: 160,
    fat: 14.7,
    carbs: 8.5,
    protein: 2,
    fiber: 6.7,
    sugar: 0.7,
    sodium: 7,
    ingredients: 'Avocado',
    description: 'Creamy fruit high in heart-healthy monounsaturated fat.'
  },
  {
    name: 'Spinach',
    category: 'Vegetables',
    serving: '100g raw',
    calories: 23,
    fat: 0.4,
    carbs: 3.6,
    protein: 2.9,
    fiber: 2.2,
    sugar: 0.4,
    sodium: 79,
    ingredients: 'Spinach leaves',
    description: 'Leafy green loaded with iron, vitamins, and antioxidants.'
  },
  {
    name: 'Whole Wheat Bread',
    category: 'Baked',
    serving: '1 slice (28g)',
    calories: 69,
    fat: 1.1,
    carbs: 12,
    protein: 3.6,
    fiber: 1.9,
    sugar: 1.4,
    sodium: 132,
    ingredients: 'Whole wheat flour, water, yeast, salt, olive oil',
    description: 'Hearty bread with whole grains and lasting energy.'
  },
  {
    name: 'Orange Juice',
    category: 'Beverages',
    serving: '240ml',
    calories: 112,
    fat: 0.5,
    carbs: 26,
    protein: 1.7,
    fiber: 0.5,
    sugar: 21,
    sodium: 2,
    ingredients: '100% orange juice',
    description: 'Refreshing vitamin C-rich drink with natural sugars.'
  },
  {
    name: 'Hard-Boiled Egg',
    category: 'Dairy',
    serving: '1 large',
    calories: 78,
    fat: 5.3,
    carbs: 0.6,
    protein: 6.3,
    fiber: 0,
    sugar: 0.6,
    sodium: 62,
    ingredients: 'Egg',
    description: 'High-quality protein and essential vitamins in a simple snack.'
  },
  {
    name: 'Greek Salad',
    category: 'Vegetables',
    serving: '1 bowl (250g)',
    calories: 180,
    fat: 11,
    carbs: 12,
    protein: 5,
    fiber: 3,
    sugar: 6,
    sodium: 450,
    ingredients: 'Tomato, cucumber, red onion, olives, feta cheese, olive oil',
    description: 'Fresh salad with Mediterranean ingredients and healthy fats.'
  },
  {
    name: 'Turkey Sandwich',
    category: 'Baked',
    serving: '1 sandwich',
    calories: 330,
    fat: 9,
    carbs: 34,
    protein: 27,
    fiber: 4,
    sugar: 4,
    sodium: 890,
    ingredients: 'Whole wheat bread, turkey breast, lettuce, tomato, mustard',
    description: 'Lean deli sandwich that balances protein, carbs, and greens.'
  },
  {
    name: 'Oatmeal',
    category: 'Grains',
    serving: '1 cup cooked',
    calories: 154,
    fat: 2.5,
    carbs: 27,
    protein: 6,
    fiber: 4,
    sugar: 1,
    sodium: 1,
    ingredients: 'Rolled oats, water',
    description: 'Warm whole-grain breakfast rich in soluble fiber.'
  },
  {
    name: 'Blueberries',
    category: 'Fruits',
    serving: '100g',
    calories: 57,
    fat: 0.3,
    carbs: 14,
    protein: 0.7,
    fiber: 2.4,
    sugar: 10,
    sodium: 1,
    ingredients: 'Blueberries',
    description: 'Antioxidant-rich fruit perfect for smoothies and snacks.'
  },
  {
    name: 'Tofu',
    category: 'Dairy',
    serving: '100g',
    calories: 76,
    fat: 4.8,
    carbs: 1.9,
    protein: 8,
    fiber: 0.3,
    sugar: 0.3,
    sodium: 7,
    ingredients: 'Soybean curd',
    description: 'Plant-based protein that soaks up flavor in many dishes.'
  },
  {
    name: 'Greek-Style Protein Bar',
    category: 'Snacks',
    serving: '1 bar (60g)',
    calories: 210,
    fat: 7,
    carbs: 22,
    protein: 15,
    fiber: 6,
    sugar: 8,
    sodium: 170,
    ingredients: 'Whole oats, whey protein, almond butter, honey',
    description: 'Convenient snack with balanced macros for energy.'
  },
  {
    name: 'Shrimp Stir-Fry',
    category: 'Seafood',
    serving: '200g',
    calories: 210,
    fat: 8,
    carbs: 12,
    protein: 24,
    fiber: 3,
    sugar: 5,
    sodium: 430,
    ingredients: 'Shrimp, broccoli, bell pepper, soy sauce, sesame oil',
    description: 'Protein-packed entree with vegetables and savory sauce.'
  },
  {
    name: 'Cottage Cheese',
    category: 'Dairy',
    serving: '113g (1/2 cup)',
    calories: 98,
    fat: 4.3,
    carbs: 3.4,
    protein: 11,
    fiber: 0,
    sugar: 2.7,
    sodium: 373,
    ingredients: 'Cottage cheese',
    description: 'Creamy dairy with high protein and mild flavor.'
  },
  {
    name: 'Apple',
    category: 'Fruits',
    serving: '1 medium (182g)',
    calories: 95,
    fat: 0.3,
    carbs: 25,
    protein: 0.5,
    fiber: 4.4,
    sugar: 19,
    sodium: 1,
    ingredients: 'Apple',
    description: 'Classic crunchy fruit with fiber and natural sweetness.'
  },
  {
    name: 'Broccoli',
    category: 'Vegetables',
    serving: '91g cooked',
    calories: 55,
    fat: 0.6,
    carbs: 11.2,
    protein: 3.7,
    fiber: 5.1,
    sugar: 2.2,
    sodium: 64,
    ingredients: 'Broccoli florets',
    description: 'Fiber-rich cruciferous vegetable packed with vitamins.'
  },
  {
    name: 'Caesar Salad',
    category: 'Vegetables',
    serving: '1 bowl (220g)',
    calories: 190,
    fat: 14,
    carbs: 12,
    protein: 7,
    fiber: 2,
    sugar: 1.5,
    sodium: 420,
    ingredients: 'Romaine lettuce, croutons, parmesan, dressing',
    description: 'Crisp salad with creamy dressing and savory toppings.'
  },
  {
    name: 'Protein Shake',
    category: 'Beverages',
    serving: '350ml',
    calories: 180,
    fat: 2.5,
    carbs: 10,
    protein: 30,
    fiber: 1,
    sugar: 4,
    sodium: 180,
    ingredients: 'Whey protein, milk, cacao powder, banana',
    description: 'Quick recovery drink that supports muscle repair.'
  },
  {
    name: 'Granola',
    category: 'Snacks',
    serving: '1/2 cup (55g)',
    calories: 220,
    fat: 9,
    carbs: 31,
    protein: 5,
    fiber: 4,
    sugar: 10,
    sodium: 95,
    ingredients: 'Oats, nuts, honey, dried fruit, seeds',
    description: 'Crunchy breakfast or snack with wholesome grains and nuts.'
  },
  {
    name: 'Turkey Bacon',
    category: 'Poultry',
    serving: '2 slices',
    calories: 70,
    fat: 4.5,
    carbs: 0,
    protein: 8,
    fiber: 0,
    sugar: 0,
    sodium: 420,
    ingredients: 'Turkey, spices, natural smoke flavor',
    description: 'Lower-fat alternative to pork bacon with smoky taste.'
  },
  {
    name: 'Mango',
    category: 'Fruits',
    serving: '1 cup sliced (165g)',
    calories: 99,
    fat: 0.6,
    carbs: 25,
    protein: 1.4,
    fiber: 2.6,
    sugar: 23,
    sodium: 1,
    ingredients: 'Mango',
    description: 'Juicy tropical fruit rich in vitamin C.'
  },
  {
    name: 'Pizza Margherita',
    category: 'Prepared',
    cuisine: 'Italian',
    serving: '1 slice (100g)',
    calories: 265,
    fat: 10,
    carbs: 33,
    protein: 11,
    fiber: 2,
    sugar: 3,
    sodium: 640,
    ingredients: 'Pizza dough, tomato sauce, mozzarella, basil',
    description: 'Classic Italian pizza with cheese, tomato, and basil.'
  },
  {
    name: 'Cheeseburger',
    category: 'Prepared',
    cuisine: 'American',
    serving: '1 burger',
    calories: 303,
    fat: 14,
    carbs: 29,
    protein: 17,
    fiber: 1.5,
    sugar: 7,
    sodium: 600,
    ingredients: 'Beef patty, bun, cheese, lettuce, tomato, sauce',
    description: 'Popular grilled burger with cheese and fresh toppings.'
  },
  {
    name: 'French Fries',
    category: 'Snacks',
    cuisine: 'American',
    serving: '117g',
    calories: 365,
    fat: 17,
    carbs: 49,
    protein: 4,
    fiber: 4.5,
    sugar: 0.3,
    sodium: 246,
    ingredients: 'Potato, vegetable oil, salt',
    description: 'Crispy fried potatoes served as a popular side dish.'
  },
  {
    name: 'Veggie Burger',
    category: 'Prepared',
    cuisine: 'American',
    serving: '1 burger',
    calories: 250,
    fat: 10,
    carbs: 29,
    protein: 12,
    fiber: 6,
    sugar: 5,
    sodium: 520,
    ingredients: 'Veggie patty, whole wheat bun, lettuce, tomato',
    description: 'Plant-based burger option with vegetables and grains.'
  },
  {
    name: 'Pasta Alfredo',
    category: 'Prepared',
    cuisine: 'Italian',
    serving: '1 cup',
    calories: 420,
    fat: 22,
    carbs: 41,
    protein: 12,
    fiber: 2,
    sugar: 3,
    sodium: 670,
    ingredients: 'Pasta, cream, parmesan, garlic, butter',
    description: 'Creamy pasta dish with rich Alfredo sauce and parmesan.'
  },
  {
    name: 'Tacos',
    category: 'Prepared',
    cuisine: 'Mexican',
    serving: '2 tacos',
    calories: 320,
    fat: 16,
    carbs: 28,
    protein: 14,
    fiber: 4,
    sugar: 3,
    sodium: 720,
    ingredients: 'Corn tortillas, seasoned meat, lettuce, salsa, cheese',
    description: 'Flavorful tacos with savory fillings and crisp toppings.'
  },
  {
    name: 'Sushi Roll',
    category: 'Prepared',
    cuisine: 'Japanese',
    serving: '6 pieces',
    calories: 255,
    fat: 5,
    carbs: 38,
    protein: 10,
    fiber: 2,
    sugar: 3,
    sodium: 420,
    ingredients: 'Rice, seaweed, avocado, cucumber, fish',
    description: 'Rice and seaweed roll with fresh vegetables and fish.'
  },
  {
    name: 'Paneer Tikka',
    category: 'Prepared',
    cuisine: 'Indian',
    serving: '100g',
    calories: 220,
    fat: 15,
    carbs: 8,
    protein: 14,
    fiber: 1.5,
    sugar: 3,
    sodium: 420,
    ingredients: 'Paneer, yogurt, spices, bell pepper',
    description: 'Marinated paneer cubes grilled with vegetables and spices.'
  },
  {
    name: 'Dosa',
    category: 'Prepared',
    cuisine: 'Indian',
    serving: '1 plain dosa (100g)',
    calories: 133,
    fat: 4,
    carbs: 20,
    protein: 3,
    fiber: 1,
    sugar: 1,
    sodium: 300,
    ingredients: 'Rice, urad dal, salt',
    description: 'Crispy South Indian crepe made from fermented rice batter.'
  },
  {
    name: 'Paratha',
    category: 'Bread',
    cuisine: 'Indian',
    serving: '1 paratha (100g)',
    calories: 230,
    fat: 12,
    carbs: 25,
    protein: 4,
    fiber: 2,
    sugar: 1,
    sodium: 320,
    ingredients: 'Whole wheat flour, ghee, salt',
    description: 'Layered Indian flatbread cooked with ghee for a flaky texture.'
  },
  {
    name: 'Chole Bhature',
    category: 'Prepared',
    cuisine: 'Indian',
    serving: '1 plate',
    size: 'medium',
    calories: 580,
    fat: 24,
    carbs: 75,
    protein: 18,
    fiber: 12,
    sugar: 6,
    sodium: 690,
    ingredients: 'Chickpea curry, fried bread, spices, yogurt',
    description: 'Hearty Punjabi dish with spiced chickpeas and fried bread.'
  },
  {
    name: 'Butter Chicken',
    category: 'Prepared',
    cuisine: 'Indian',
    serving: '1 cup (240g)',
    calories: 320,
    fat: 18,
    carbs: 10,
    protein: 24,
    fiber: 2,
    sugar: 5,
    sodium: 610,
    ingredients: 'Chicken, butter, cream, tomato, spices',
    description: 'Creamy tomato-based curry with tender chicken pieces.'
  },
  {
    name: 'Biryani',
    category: 'Prepared',
    cuisine: 'Indian',
    serving: '1 cup',
    calories: 290,
    fat: 12,
    carbs: 34,
    protein: 12,
    fiber: 2,
    sugar: 3,
    sodium: 520,
    ingredients: 'Basmati rice, meat, spices, yogurt, herbs',
    description: 'Fragrant spiced rice dish made with meat or vegetables.'
  },
  {
    name: 'Samosa',
    category: 'Snacks',
    cuisine: 'Indian',
    serving: '1 piece',
    size: 'medium',
    calories: 150,
    fat: 8,
    carbs: 17,
    protein: 3,
    fiber: 2,
    sugar: 1,
    sodium: 170,
    ingredients: 'Potato, peas, pastry, spices, oil',
    description: 'Crispy fried pastry filled with spicy potatoes and peas.'
  },
  {
    name: 'Idli',
    category: 'Prepared',
    cuisine: 'Indian',
    serving: '2 pieces',
    size: 'medium',
    calories: 140,
    fat: 1,
    carbs: 28,
    protein: 4,
    fiber: 1,
    sugar: 1,
    sodium: 220,
    ingredients: 'Rice, urad dal, salt',
    description: 'Steamed rice cakes served with chutney and sambar.'
  },
  {
    name: 'Naan',
    category: 'Bread',
    cuisine: 'Indian',
    serving: '1 piece',
    size: 'medium',
    calories: 290,
    fat: 9,
    carbs: 44,
    protein: 8,
    fiber: 2,
    sugar: 3,
    sodium: 560,
    ingredients: 'Wheat flour, yogurt, yeast, butter',
    description: 'Soft Indian flatbread baked in a tandoor oven.'
  },
  {
    name: 'Gulab Jamun',
    category: 'Desserts',
    serving: '1 piece',
    calories: 150,
    fat: 5,
    carbs: 24,
    protein: 2,
    fiber: 0,
    sugar: 18,
    sodium: 35,
    ingredients: 'Milk solids, sugar syrup, cardamom',
    description: 'Sweet Indian dessert made from fried milk dough in syrup.'
  },
  {
    name: 'Mango Lassi',
    category: 'Beverages',
    serving: '250ml',
    calories: 210,
    fat: 6,
    carbs: 38,
    protein: 6,
    fiber: 1,
    sugar: 32,
    sodium: 90,
    ingredients: 'Yogurt, mango pulp, milk, sugar',
    description: 'Creamy sweet mango yogurt drink from India.'
  },
  {
    name: 'Aloo Paratha',
    category: 'Bread',
    cuisine: 'Indian',
    serving: '1 paratha',
    size: 'medium',
    calories: 260,
    fat: 12,
    carbs: 32,
    protein: 5,
    fiber: 3,
    sugar: 1,
    sodium: 320,
    ingredients: 'Whole wheat flour, potato, spices, ghee',
    description: 'Flatbread stuffed with spiced mashed potatoes.'
  },
  {
    name: 'Dal Tadka',
    category: 'Prepared',
    cuisine: 'Indian',
    serving: '1 cup',
    calories: 180,
    fat: 8,
    carbs: 20,
    protein: 9,
    fiber: 6,
    sugar: 2,
    sodium: 450,
    ingredients: 'Yellow lentils, tomato, garlic, ghee, spices',
    description: 'Lentil curry tempered with aromatic spices.'
  },
  {
    name: 'Rajma Chawal',
    category: 'Prepared',
    cuisine: 'Indian',
    serving: '1 plate',
    calories: 360,
    fat: 10,
    carbs: 57,
    protein: 15,
    fiber: 11,
    sugar: 4,
    sodium: 560,
    ingredients: 'Kidney beans, rice, tomato sauce, spices',
    description: 'Comforting North Indian meal of kidney beans and rice.'
  },
  {
    name: 'Pav Bhaji',
    category: 'Prepared',
    cuisine: 'Indian',
    serving: '1 plate',
    size: 'medium',
    calories: 350,
    fat: 14,
    carbs: 52,
    protein: 9,
    fiber: 8,
    sugar: 8,
    sodium: 680,
    ingredients: 'Vegetable mash, butter, pav buns, spices',
    description: 'Spiced vegetable mash served with buttered buns.'
  },
  {
    name: 'Pani Puri',
    category: 'Snacks',
    cuisine: 'Indian',
    serving: '6 pieces',
    size: 'small',
    calories: 240,
    fat: 8,
    carbs: 36,
    protein: 4,
    fiber: 4,
    sugar: 6,
    sodium: 540,
    ingredients: 'Semolina shells, tamarind water, potato, chickpeas',
    description: 'Crispy hollow puris filled with spicy water and chutney.'
  },
  {
    name: 'Masala Chai',
    category: 'Beverages',
    cuisine: 'Indian',
    serving: '250ml',
    calories: 120,
    fat: 4,
    carbs: 18,
    protein: 2,
    fiber: 0,
    sugar: 15,
    sodium: 40,
    ingredients: 'Tea, milk, cardamom, ginger, sugar',
    description: 'Warm spiced Indian tea brewed with milk and aromatic masalas.'
  },
  {
    name: 'Paneer Butter Masala',
    category: 'Prepared',
    cuisine: 'Indian',
    serving: '1 cup',
    calories: 310,
    fat: 22,
    carbs: 12,
    protein: 13,
    fiber: 2,
    sugar: 5,
    sodium: 620,
    ingredients: 'Paneer, tomato, butter, cream, spices',
    description: 'Creamy Indian curry with soft paneer cubes in buttery tomato gravy.'
  },
  {
    name: 'Chicken Tikka Masala',
    category: 'Prepared',
    cuisine: 'Indian',
    serving: '1 cup',
    calories: 350,
    fat: 18,
    carbs: 14,
    protein: 25,
    fiber: 2,
    sugar: 6,
    sodium: 700,
    ingredients: 'Chicken, tomato, cream, spices, yogurt',
    description: 'Popular Indian curry with grilled chicken pieces in a rich tomato sauce.'
  },
  {
    name: 'Jalebi',
    category: 'Desserts',
    cuisine: 'Indian',
    serving: '1 piece',
    size: 'small',
    calories: 125,
    fat: 6,
    carbs: 16,
    protein: 1,
    fiber: 0,
    sugar: 10,
    sodium: 50,
    ingredients: 'Flour, sugar syrup, ghee, saffron',
    description: 'Sweet Indian dessert made from deep-fried batter soaked in syrup.'
  },
  {
    name: 'Dhokla',
    category: 'Snacks',
    cuisine: 'Indian',
    serving: '100g',
    calories: 150,
    fat: 5,
    carbs: 22,
    protein: 6,
    fiber: 2,
    sugar: 3,
    sodium: 450,
    ingredients: 'Gram flour, yogurt, green chili, mustard seeds',
    description: 'Soft steamed snack from Gujarat, served with chutney.'
  },
  {
    name: 'Vada Pav',
    category: 'Prepared',
    cuisine: 'Indian',
    serving: '1 sandwich',
    calories: 300,
    fat: 12,
    carbs: 40,
    protein: 6,
    fiber: 4,
    sugar: 6,
    sodium: 520,
    ingredients: 'Potato fritter, bun, chutney, garlic paste',
    description: 'Mumbai street food sandwich with spicy potato fritter and sauces.'
  },
  {
    name: 'Palak Paneer',
    category: 'Prepared',
    cuisine: 'Indian',
    serving: '1 cup',
    calories: 260,
    fat: 18,
    carbs: 10,
    protein: 12,
    fiber: 4,
    sugar: 3,
    sodium: 620,
    ingredients: 'Spinach, paneer, garlic, ginger, spices',
    description: 'Creamy spinach curry cooked with paneer cubes and spices.'
  },
  {
    name: 'Aloo Tikki',
    category: 'Snacks',
    cuisine: 'Indian',
    serving: '1 piece',
    size: 'medium',
    calories: 130,
    fat: 6,
    carbs: 18,
    protein: 2,
    fiber: 2,
    sugar: 1,
    sodium: 160,
    ingredients: 'Potato, spices, bread crumbs, oil',
    description: 'Crispy potato patty served with chutney and spices.'
  },
  {
    name: 'Chocolate Cake',
    category: 'Desserts',
    serving: '1 slice (80g)',
    calories: 360,
    fat: 18,
    carbs: 47,
    protein: 4,
    fiber: 2,
    sugar: 32,
    sodium: 250,
    ingredients: 'Flour, cocoa, sugar, butter, eggs',
    description: 'Moist chocolate cake with rich chocolate frosting.'
  },
  {
    name: 'Strawberries',
    category: 'Fruits',
    serving: '100g',
    calories: 32,
    fat: 0.3,
    carbs: 7.7,
    protein: 0.7,
    fiber: 2,
    sugar: 4.9,
    sodium: 1,
    ingredients: 'Strawberries',
    description: 'Sweet, juicy berries with plenty of vitamin C.'
  },
  {
    name: 'Tomato',
    category: 'Vegetables',
    serving: '100g',
    calories: 18,
    fat: 0.2,
    carbs: 3.9,
    protein: 0.9,
    fiber: 1.2,
    sugar: 2.6,
    sodium: 5,
    ingredients: 'Tomato',
    description: 'Juicy tomato used in salads, sauces, and curries.'
  },
  {
    name: 'Cucumber',
    category: 'Vegetables',
    serving: '100g',
    calories: 16,
    fat: 0.1,
    carbs: 3.6,
    protein: 0.7,
    fiber: 0.5,
    sugar: 1.7,
    sodium: 2,
    ingredients: 'Cucumber',
    description: 'Cool, hydrating vegetable ideal for salads and snacks.'
  },
  {
    name: 'Pineapple',
    category: 'Fruits',
    serving: '100g',
    calories: 50,
    fat: 0.1,
    carbs: 13,
    protein: 0.5,
    fiber: 1.4,
    sugar: 10,
    sodium: 1,
    ingredients: 'Pineapple',
    description: 'Tropical fruit with bright sweetness and vitamin C.'
  },
  {
    name: 'Kung Pao Chicken',
    category: 'Chinese',
    cuisine: 'Chinese',
    serving: '1 cup',
    calories: 290,
    fat: 17,
    carbs: 13,
    protein: 20,
    fiber: 2,
    sugar: 7,
    sodium: 820,
    ingredients: 'Chicken, peanuts, peppers, soy sauce, chili',
    description: 'Spicy Chinese stir-fry with chicken, peanuts and peppers.'
  },
  {
    name: 'Fried Rice',
    category: 'Chinese',
    cuisine: 'Chinese',
    serving: '1 cup',
    calories: 238,
    fat: 10,
    carbs: 33,
    protein: 7,
    fiber: 1.5,
    sugar: 2,
    sodium: 640,
    ingredients: 'Rice, egg, vegetables, soy sauce, sesame oil',
    description: 'Savory Chinese rice dish with scrambled egg and veggies.'
  },
  {
    name: 'Spring Rolls',
    category: 'Chinese',
    cuisine: 'Chinese',
    serving: '2 rolls',
    calories: 160,
    fat: 8,
    carbs: 18,
    protein: 4,
    fiber: 2,
    sugar: 3,
    sodium: 420,
    ingredients: 'Vegetables, rice paper, soy sauce',
    description: 'Crispy Chinese appetizers filled with fresh vegetables.'
  },
  {
    name: 'Tacos Al Pastor',
    category: 'Mexican',
    cuisine: 'Mexican',
    serving: '2 tacos',
    calories: 360,
    fat: 18,
    carbs: 32,
    protein: 16,
    fiber: 4,
    sugar: 4,
    sodium: 760,
    ingredients: 'Corn tortillas, pork, pineapple, onion, cilantro',
    description: 'Flavorful Mexican tacos with marinated pork and pineapple.'
  },
  {
    name: 'Guacamole',
    category: 'Snacks',
    cuisine: 'Mexican',
    serving: '100g',
    calories: 146,
    fat: 13,
    carbs: 8,
    protein: 2,
    fiber: 7,
    sugar: 0.7,
    sodium: 270,
    ingredients: 'Avocado, lime, tomato, onion, cilantro',
    description: 'Creamy avocado dip with lime and fresh herbs.'
  },
  {
    name: 'Burrito',
    category: 'Prepared',
    cuisine: 'Mexican',
    serving: '1 burrito',
    calories: 560,
    fat: 22,
    carbs: 64,
    protein: 18,
    fiber: 8,
    sugar: 4,
    sodium: 1020,
    ingredients: 'Tortilla, rice, beans, cheese, meat, salsa',
    description: 'Hearty Mexican wrap loaded with beans, cheese and salsa.'
  },
  {
    name: 'Spaghetti Bolognese',
    category: 'Prepared',
    cuisine: 'Italian',
    serving: '1 plate',
    calories: 340,
    fat: 12,
    carbs: 45,
    protein: 18,
    fiber: 4,
    sugar: 6,
    sodium: 600,
    ingredients: 'Pasta, beef sauce, tomato, herbs, parmesan',
    description: 'Italian pasta dish with rich meat sauce and Parmesan.'
  },
  {
    name: 'Lasagna',
    category: 'Prepared',
    cuisine: 'Italian',
    serving: '1 slice',
    calories: 324,
    fat: 18,
    carbs: 24,
    protein: 18,
    fiber: 3,
    sugar: 5,
    sodium: 610,
    ingredients: 'Pasta sheets, ricotta, tomato sauce, cheese, beef',
    description: 'Layered Italian casserole with meat, cheese and pasta.'
  },
  {
    name: 'Ratatouille',
    category: 'Prepared',
    cuisine: 'French',
    serving: '1 cup',
    calories: 150,
    fat: 8,
    carbs: 16,
    protein: 3,
    fiber: 5,
    sugar: 9,
    sodium: 260,
    ingredients: 'Zucchini, eggplant, tomato, bell pepper, herbs',
    description: 'Classic French vegetable stew with herbs and olive oil.'
  },
  {
    name: 'Croissant',
    category: 'Baked',
    cuisine: 'French',
    serving: '1 croissant (57g)',
    calories: 231,
    fat: 12,
    carbs: 26,
    protein: 5,
    fiber: 1,
    sugar: 4,
    sodium: 290,
    ingredients: 'Flour, butter, milk, sugar, yeast',
    description: 'Flaky French pastry with rich buttery layers.'
  },
  {
    name: 'Ramen',
    category: 'Prepared',
    cuisine: 'Japanese',
    serving: '1 bowl',
    calories: 436,
    fat: 17,
    carbs: 52,
    protein: 18,
    fiber: 3,
    sugar: 4,
    sodium: 1200,
    ingredients: 'Noodles, broth, pork, egg, vegetables',
    description: 'Savory Japanese noodle soup with rich broth and toppings.'
  },
  {
    name: 'Miso Soup',
    category: 'Prepared',
    cuisine: 'Japanese',
    serving: '1 cup',
    calories: 40,
    fat: 1.5,
    carbs: 5,
    protein: 3,
    fiber: 1,
    sugar: 1,
    sodium: 800,
    ingredients: 'Miso paste, tofu, seaweed, scallion, dashi',
    description: 'Light Japanese soup made with miso, tofu, and seaweed.'
  },
  {
    name: 'Pad Thai',
    category: 'Prepared',
    cuisine: 'Thai',
    serving: '1 plate',
    calories: 430,
    fat: 16,
    carbs: 53,
    protein: 17,
    fiber: 4,
    sugar: 9,
    sodium: 780,
    ingredients: 'Rice noodles, egg, shrimp, peanuts, tamarind sauce',
    description: 'Popular Thai noodle dish with tangy sauce and peanuts.'
  },
  {
    name: 'Green Curry',
    category: 'Prepared',
    cuisine: 'Thai',
    serving: '1 cup',
    calories: 280,
    fat: 22,
    carbs: 12,
    protein: 8,
    fiber: 1,
    sugar: 3,
    sodium: 690,
    ingredients: 'Coconut milk, green curry paste, chicken, basil',
    description: 'Aromatic Thai curry made with coconut milk and green chilies.'
  },
  {
    name: 'Hummus',
    category: 'Middle Eastern',
    cuisine: 'Middle Eastern',
    serving: '100g',
    calories: 166,
    fat: 9.6,
    carbs: 14,
    protein: 7.9,
    fiber: 6,
    sugar: 0.3,
    sodium: 240,
    ingredients: 'Chickpeas, tahini, olive oil, lemon, garlic',
    description: 'Creamy Middle Eastern dip made from chickpeas and tahini.'
  },
  {
    name: 'Falafel Wrap',
    category: 'Prepared',
    cuisine: 'Middle Eastern',
    serving: '1 wrap',
    calories: 360,
    fat: 14,
    carbs: 45,
    protein: 12,
    fiber: 8,
    sugar: 4,
    sodium: 560,
    ingredients: 'Pita bread, falafel, tahini, lettuce, tomato',
    description: 'Vegetarian wrap with crispy chickpea patties and sauce.'
  },
  {
    name: 'Shawarma',
    category: 'Prepared',
    cuisine: 'Middle Eastern',
    serving: '1 wrap',
    calories: 430,
    fat: 18,
    carbs: 42,
    protein: 22,
    fiber: 4,
    sugar: 6,
    sodium: 920,
    ingredients: 'Flatbread, seasoned meat, tahini, pickles, vegetables',
    description: 'Savory Middle Eastern wrap with spiced meat and vegetables.'
  },
  {
    name: 'Paella',
    category: 'Prepared',
    cuisine: 'Spanish',
    serving: '1 cup',
    calories: 280,
    fat: 10,
    carbs: 35,
    protein: 12,
    fiber: 3,
    sugar: 2,
    sodium: 540,
    ingredients: 'Rice, seafood, saffron, vegetables, chicken',
    description: 'Spanish rice dish with saffron, seafood, and vegetables.'
  },
  {
    name: 'Churros',
    category: 'Desserts',
    cuisine: 'Spanish',
    serving: '3 pieces',
    calories: 220,
    fat: 11,
    carbs: 26,
    protein: 2,
    fiber: 1,
    sugar: 9,
    sodium: 180,
    ingredients: 'Flour, sugar, oil, cinnamon',
    description: 'Fried Spanish doughnuts dusted with cinnamon sugar.'
  }
];

const searchInput = document.getElementById('searchInput');
const categorySelect = document.getElementById('categorySelect');
const cuisineSelect = document.getElementById('cuisineSelect');
const sortSelect = document.getElementById('sortSelect');
const resultsCount = document.getElementById('resultsCount');
const foodList = document.getElementById('foodList');
const clearSearch = document.getElementById('clearSearch');

function createFoodCard(item) {
  const card = document.createElement('article');
  card.className = 'food-card';
  const servingDetails = item.serving + (item.weight ? ` (${item.weight}g)` : item.size ? ` (${item.size})` : '');
  card.innerHTML = `
    <div>
      <div class="badge">${item.category}</div>
      <div class="badge">${item.cuisine || 'Global'}</div>
      <h3>${item.name}</h3>
      <p class="food-meta">${servingDetails} · ${item.description}</p>
    </div>
    <div class="nutrition-grid">
      <div class="nutrition-item"><strong>Calories</strong><span>${item.calories} kcal</span></div>
      <div class="nutrition-item"><strong>Protein</strong><span>${item.protein} g</span></div>
      <div class="nutrition-item"><strong>Fat</strong><span>${item.fat} g</span></div>
      <div class="nutrition-item"><strong>Carbs</strong><span>${item.carbs} g</span></div>
      <div class="nutrition-item"><strong>Fiber</strong><span>${item.fiber} g</span></div>
      <div class="nutrition-item"><strong>Sugar</strong><span>${item.sugar} g</span></div>
      <div class="nutrition-item"><strong>Sodium</strong><span>${item.sodium} mg</span></div>
    </div>
    <p class="ingredients"><strong>Ingredients:</strong> ${item.ingredients}</p>
  `;
  return card;
}

function getFilteredFoods() {
  const query = searchInput.value.trim().toLowerCase();
  const category = categorySelect.value;
  const cuisine = cuisineSelect.value;

  return foods
    .filter((item) => {
      const itemCuisine = item.cuisine || 'Global';
      const text = `${item.name} ${item.category} ${itemCuisine} ${item.ingredients} ${item.description}`.toLowerCase();
      const matchesQuery = query === '' || text.includes(query);
      const matchesCategory = query !== '' ? true : category === 'all' || item.category === category;
      const matchesCuisine = query !== '' ? true : cuisine === 'all' || itemCuisine === cuisine;
      return matchesQuery && matchesCategory && matchesCuisine;
    })
    .sort((a, b) => {
      const sortBy = sortSelect.value;
      if (sortBy === 'calories') return a.calories - b.calories;
      if (sortBy === 'protein') return b.protein - a.protein;
      if (sortBy === 'fat') return a.fat - b.fat;
      return a.name.localeCompare(b.name);
    });
}

function renderFoods() {
  const filtered = getFilteredFoods();
  foodList.innerHTML = '';
  resultsCount.textContent = filtered.length;

  if (filtered.length === 0) {
    const emptyState = document.createElement('div');
    emptyState.className = 'food-card';
    emptyState.innerHTML = '<h3>No foods matched your search.</h3><p>Try a different keyword, nutrient, or category.</p>';
    foodList.appendChild(emptyState);
    return;
  }

  filtered.forEach((item) => {
    foodList.appendChild(createFoodCard(item));
  });
}

searchInput.addEventListener('input', renderFoods);
categorySelect.addEventListener('change', renderFoods);
cuisineSelect.addEventListener('change', renderFoods);
sortSelect.addEventListener('change', renderFoods);
clearSearch.addEventListener('click', () => {
  searchInput.value = '';
  categorySelect.value = 'all';
  cuisineSelect.value = 'all';
  sortSelect.value = 'name';
  searchInput.focus();
  renderFoods();
});

renderFoods();
